#cloud-config
packages:
 - curl
 - wget
 - jq
 - git
 - buildah

runcmd:
 - |
   set -x
   curl https://raw.githubusercontent.com/NethServer/ns8-core/${install_branch}/core/install.sh | bash -s ${pull_branch} ${pull_modules}
