#cloud-config
packages:
 - curl
 - wget
 - jq
 - git
 - buildah

users:
 - name: cloud-user
   ssh_authorized_keys:
     %{~ for sshkey in sshkeys ~}
     - |
       ${sshkey}
     %{~ endfor ~}

runcmd:
 - |
   set -x
   curl https://raw.githubusercontent.com/NethServer/ns8-core/${install_branch}/core/install.sh | bash -s ${pull_branch} ${pull_modules}
